services:
  mysql:
    image: mysql:8.4
    container_name: alvaraes-moderna-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: alvaraes_moderna
      MYSQL_USER: alvaraes
      MYSQL_PASSWORD: alvaraes123456
    ports:
      - "3306:3306"
    volumes:
      - alvaraes_moderna_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  alvaraes_moderna_mysql_data:
