/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as BoletimRouteImport } from './routes/boletim'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBoletimRouteImport } from './routes/admin/boletim'
import { Route as AdminComentariosRouteImport } from './routes/admin/comentarios'
import { Route as AdminComerciosRouteImport } from './routes/admin/comercios'
import { Route as AdminContatosRouteImport } from './routes/admin/contatos'
import { Route as AdminCursosRouteImport } from './routes/admin/cursos'
import { Route as AdminEventosRouteImport } from './routes/admin/eventos'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminNoticiasRouteImport } from './routes/admin/noticias'
import { Route as AdminPedidosAnuncioRouteImport } from './routes/admin/pedidos-anuncio'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AgendaIndexRouteImport } from './routes/agenda/index'
import { Route as AgendaIdRouteImport } from './routes/agenda/$id'
import { Route as ComerciosIndexRouteImport } from './routes/comercios/index'
import { Route as ComerciosSlugRouteImport } from './routes/comercios/$slug'
import { Route as CursosIndexRouteImport } from './routes/cursos/index'
import { Route as CursosIdRouteImport } from './routes/cursos/$id'
import { Route as NoticiasIndexRouteImport } from './routes/noticias/index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const BoletimRoute = BoletimRouteImport.update({
  id: '/boletim',
  path: '/boletim',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBoletimRoute = AdminBoletimRouteImport.update({
  id: '/admin/boletim',
  path: '/admin/boletim',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComentariosRoute = AdminComentariosRouteImport.update({
  id: '/admin/comentarios',
  path: '/admin/comentarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComerciosRoute = AdminComerciosRouteImport.update({
  id: '/admin/comercios',
  path: '/admin/comercios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContatosRoute = AdminContatosRouteImport.update({
  id: '/admin/contatos',
  path: '/admin/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosRoute = AdminCursosRouteImport.update({
  id: '/admin/cursos',
  path: '/admin/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/admin/eventos',
  path: '/admin/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNoticiasRoute = AdminNoticiasRouteImport.update({
  id: '/admin/noticias',
  path: '/admin/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosAnuncioRoute = AdminPedidosAnuncioRouteImport.update({
  id: '/admin/pedidos-anuncio',
  path: '/admin/pedidos-anuncio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaIndexRoute = AgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaIdRoute = AgendaIdRouteImport.update({
  id: '/agenda/$id',
  path: '/agenda/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComerciosIndexRoute = ComerciosIndexRouteImport.update({
  id: '/comercios/',
  path: '/comercios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComerciosSlugRoute = ComerciosSlugRouteImport.update({
  id: '/comercios/$slug',
  path: '/comercios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIdRoute = CursosIdRouteImport.update({
  id: '/cursos/$id',
  path: '/cursos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/boletim': typeof BoletimRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/admin/boletim': typeof AdminBoletimRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/comercios': typeof AdminComerciosRoute
  '/admin/contatos': typeof AdminContatosRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/pedidos-anuncio': typeof AdminPedidosAnuncioRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/agenda/$id': typeof AgendaIdRoute
  '/comercios/$slug': typeof ComerciosSlugRoute
  '/cursos/$id': typeof CursosIdRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/agenda/': typeof AgendaIndexRoute
  '/comercios/': typeof ComerciosIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/boletim': typeof BoletimRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/admin/boletim': typeof AdminBoletimRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/comercios': typeof AdminComerciosRoute
  '/admin/contatos': typeof AdminContatosRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/pedidos-anuncio': typeof AdminPedidosAnuncioRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/agenda/$id': typeof AgendaIdRoute
  '/comercios/$slug': typeof ComerciosSlugRoute
  '/cursos/$id': typeof CursosIdRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/admin': typeof AdminIndexRoute
  '/agenda': typeof AgendaIndexRoute
  '/comercios': typeof ComerciosIndexRoute
  '/cursos': typeof CursosIndexRoute
  '/noticias': typeof NoticiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/boletim': typeof BoletimRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/admin/boletim': typeof AdminBoletimRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/comercios': typeof AdminComerciosRoute
  '/admin/contatos': typeof AdminContatosRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/pedidos-anuncio': typeof AdminPedidosAnuncioRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/agenda/$id': typeof AgendaIdRoute
  '/comercios/$slug': typeof ComerciosSlugRoute
  '/cursos/$id': typeof CursosIdRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/agenda/': typeof AgendaIndexRoute
  '/comercios/': typeof ComerciosIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anuncie'
    | '/boletim'
    | '/contato'
    | '/privacidade'
    | '/sobre'
    | '/admin/boletim'
    | '/admin/comentarios'
    | '/admin/comercios'
    | '/admin/contatos'
    | '/admin/cursos'
    | '/admin/eventos'
    | '/admin/login'
    | '/admin/noticias'
    | '/admin/pedidos-anuncio'
    | '/admin/usuarios'
    | '/agenda/$id'
    | '/comercios/$slug'
    | '/cursos/$id'
    | '/noticias/$slug'
    | '/admin/'
    | '/agenda/'
    | '/comercios/'
    | '/cursos/'
    | '/noticias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncie'
    | '/boletim'
    | '/contato'
    | '/privacidade'
    | '/sobre'
    | '/admin/boletim'
    | '/admin/comentarios'
    | '/admin/comercios'
    | '/admin/contatos'
    | '/admin/cursos'
    | '/admin/eventos'
    | '/admin/login'
    | '/admin/noticias'
    | '/admin/pedidos-anuncio'
    | '/admin/usuarios'
    | '/agenda/$id'
    | '/comercios/$slug'
    | '/cursos/$id'
    | '/noticias/$slug'
    | '/admin'
    | '/agenda'
    | '/comercios'
    | '/cursos'
    | '/noticias'
  id:
    | '__root__'
    | '/'
    | '/anuncie'
    | '/boletim'
    | '/contato'
    | '/privacidade'
    | '/sobre'
    | '/admin/boletim'
    | '/admin/comentarios'
    | '/admin/comercios'
    | '/admin/contatos'
    | '/admin/cursos'
    | '/admin/eventos'
    | '/admin/login'
    | '/admin/noticias'
    | '/admin/pedidos-anuncio'
    | '/admin/usuarios'
    | '/agenda/$id'
    | '/comercios/$slug'
    | '/cursos/$id'
    | '/noticias/$slug'
    | '/admin/'
    | '/agenda/'
    | '/comercios/'
    | '/cursos/'
    | '/noticias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnuncieRoute: typeof AnuncieRoute
  BoletimRoute: typeof BoletimRoute
  ContatoRoute: typeof ContatoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  AdminBoletimRoute: typeof AdminBoletimRoute
  AdminComentariosRoute: typeof AdminComentariosRoute
  AdminComerciosRoute: typeof AdminComerciosRoute
  AdminContatosRoute: typeof AdminContatosRoute
  AdminCursosRoute: typeof AdminCursosRoute
  AdminEventosRoute: typeof AdminEventosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNoticiasRoute: typeof AdminNoticiasRoute
  AdminPedidosAnuncioRoute: typeof AdminPedidosAnuncioRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AgendaIdRoute: typeof AgendaIdRoute
  ComerciosSlugRoute: typeof ComerciosSlugRoute
  CursosIdRoute: typeof CursosIdRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AgendaIndexRoute: typeof AgendaIndexRoute
  ComerciosIndexRoute: typeof ComerciosIndexRoute
  CursosIndexRoute: typeof CursosIndexRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boletim': {
      id: '/boletim'
      path: '/boletim'
      fullPath: '/boletim'
      preLoaderRoute: typeof BoletimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/boletim': {
      id: '/admin/boletim'
      path: '/admin/boletim'
      fullPath: '/admin/boletim'
      preLoaderRoute: typeof AdminBoletimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/comentarios': {
      id: '/admin/comentarios'
      path: '/admin/comentarios'
      fullPath: '/admin/comentarios'
      preLoaderRoute: typeof AdminComentariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/comercios': {
      id: '/admin/comercios'
      path: '/admin/comercios'
      fullPath: '/admin/comercios'
      preLoaderRoute: typeof AdminComerciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contatos': {
      id: '/admin/contatos'
      path: '/admin/contatos'
      fullPath: '/admin/contatos'
      preLoaderRoute: typeof AdminContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos': {
      id: '/admin/cursos'
      path: '/admin/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminCursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/admin/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/noticias': {
      id: '/admin/noticias'
      path: '/admin/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AdminNoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos-anuncio': {
      id: '/admin/pedidos-anuncio'
      path: '/admin/pedidos-anuncio'
      fullPath: '/admin/pedidos-anuncio'
      preLoaderRoute: typeof AdminPedidosAnuncioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/': {
      id: '/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AgendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/$id': {
      id: '/agenda/$id'
      path: '/agenda/$id'
      fullPath: '/agenda/$id'
      preLoaderRoute: typeof AgendaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercios/': {
      id: '/comercios/'
      path: '/comercios'
      fullPath: '/comercios/'
      preLoaderRoute: typeof ComerciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercios/$slug': {
      id: '/comercios/$slug'
      path: '/comercios/$slug'
      fullPath: '/comercios/$slug'
      preLoaderRoute: typeof ComerciosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$id': {
      id: '/cursos/$id'
      path: '/cursos/$id'
      fullPath: '/cursos/$id'
      preLoaderRoute: typeof CursosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnuncieRoute: AnuncieRoute,
  BoletimRoute: BoletimRoute,
  ContatoRoute: ContatoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  AdminBoletimRoute: AdminBoletimRoute,
  AdminComentariosRoute: AdminComentariosRoute,
  AdminComerciosRoute: AdminComerciosRoute,
  AdminContatosRoute: AdminContatosRoute,
  AdminCursosRoute: AdminCursosRoute,
  AdminEventosRoute: AdminEventosRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNoticiasRoute: AdminNoticiasRoute,
  AdminPedidosAnuncioRoute: AdminPedidosAnuncioRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AgendaIdRoute: AgendaIdRoute,
  ComerciosSlugRoute: ComerciosSlugRoute,
  CursosIdRoute: CursosIdRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AgendaIndexRoute: AgendaIndexRoute,
  ComerciosIndexRoute: ComerciosIndexRoute,
  CursosIndexRoute: CursosIndexRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
